# Generated by Django 4.0.3 on 2022-04-15 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
