# Generated by Django 4.0.3 on 2022-04-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
